apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "node" group to read nodes in any namespace.
kind: ClusterRoleBinding
metadata:
  name: node-manager
subjects:
- kind: User
  name: michelle # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: node-clusterrole
  apiGroup: rbac.authorization.k8s.io

---


apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "node" group to read nodes in any namespace.
kind: ClusterRoleBinding
metadata:
  name: michelle-storage-admin
subjects:
- kind: User
  name: michelle # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: storage-admin
  apiGroup: rbac.authorization.k8s.io


