apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: momo
spec:
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZEQ0NBVHdDQVFBd0R6RU5NQXNHQTFVRUF3d0ViVzl0YnpDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRApnZ0VQQURDQ0FRb0NnZ0VCQUpMVHVqQmRhNnNrZHBGUUJPZG5ZYkttWGFHSC95a2YxRVJLbmdUenBlcE9IajZ1CndiV3FQN0ZYZ0dyZlhIK082dkk5VlBBVDVXNG11Z2ZEeXd6dFM1NWdKOXFlb2t5b3pxUjJjbTFuaU85ZlpKY2oKMEFuM0x6aGFIb2d2aVFINDZwUE51a0U1d0V1YVc5Vk9OczhiTGd2RmhQa0M3SzllS1QwOFpoZWl1eGtsbHRoUQo1YnlnajJiN3JxK2NWeE1pWkZsRFRtd2hCWEQ2Z0M2UFo4NjYvWnVvRGJiTkhpb21GdFQ2Z1Z2Z1EvWG4rdlBVCjFhREQ2WHBtVUNpdVg1d3JsNUxaRWp6eXZXak5MVHVrSGUrM3pHWHp1Z2hkeVFaSTF5WGR0S1YxLzJBbStjTzIKM3FZUHlBTWxnNUgzQWV3UXpWYTZJYUxwTDRBZ1p6blZVUCtyYldzQ0F3RUFBYUFBTUEwR0NTcUdTSWIzRFFFQgpDd1VBQTRJQkFRQXZrblprYXY4MjlRVkZOL1M5eEtnVEFtenNSRWFuWkNMaHVyaHh4M1FCZjlYanBSZU9nc2o0Ck1wS1ErbjR3QlRndjFTOFJta1I2RVdXWDFQSUNoMlhCWmRwNUNrYzFDQk96aTRhdGltUG5PL0kvVjBPclFPYzcKWXRnZEtJMFh2ZTd1Zm5tQTdRcmNRQVNuOWNueExRUXNBdjMxRDJuYWVhY203RGZBN3lkeW1od2NHT0k1alZWRwp0cW9yODNSdFN4elg1UDJDZXB2Rk5SZTVzKzAwakd0c2dJejJxOU9KcHVITyt0NDdpaUhrdm5TbzJCQzQ3Y1ZUCmRXTTFZNTFmSG1BREpMa3RmSkZhN0VxcFlOOG1wSUFydVNRNWxEM3IzTDgwYzRZNmZnRGtuZnQ1SnptckhReXIKck9Na1k4ZFU0cllHa0VLNTN4OEdPTW5TTUxxNHh5bnQKLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==
  signerName: kubernetes.io/kube-apiserver-client
  usages:
    - client auth 
  groups:
    - system:masters
    