apiVersion: v1
kind: Pod 
metadata:
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
  schedulerName: my-scheduler

---

apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
profiles:
 - schedulerName: default-scheduler
 
 ---

# To check the events use the command kubectl get events -o wide 
# to check the scheduler name > kubectl logs my-custom-scheduler --name-space=kube-system