apiVersion: v1
kind: ResourceQuota
metadata:
  name: my-resource-quota
  namespace: dev
spec:
  hard:
    requests.cpu: "100m"
    requests.memory: "64Mi"
    limits.cpu: "500m"
    limits.memory: "128Mi"


# Makesure you have namespace created if you are applying it on different namespace
# to check the resource quotas command kubectl describe quota -n=dev``