# To create a service account use the command > kubectl create sa jenkins-sa

apiVersion: v1
kind: Secret
metadata:
  name: build-jenkinsa-secret
  annotations:
    kubernetes.io/service-account.name: jenkins-sa
type: kubernetes.io/service-account-token

# kubectl apply -f secret.yaml

# to create access troken kubectl create token dashboard-sa

# Once Service Account and Secret is created you need to to give RBAC like roles and role bindings to Service Account. 